package com.personalos.backend.fitness.dto;

import com.personalos.backend.fitness.domain.PersonalRecordType;
import com.personalos.backend.fitness.domain.WorkoutStatus;
import com.personalos.backend.fitness.dto.ExerciseDtos.ExerciseResponse;
import jakarta.validation.constraints.*;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

public final class WorkoutDtos {

    private WorkoutDtos() {
    }

    // ---- requests ----------------------------------------------------------------------------

    public record StartWorkoutRequest(
            UUID templateId,
            @Size(max = 100) @Pattern(regexp = ".*\\S.*", message = "must not be blank") String name
    ) {}

    /** Both optional, at least one required. A blank {@code notes} clears them. */
    public record UpdateWorkoutRequest(
            @Size(max = 100) @Pattern(regexp = ".*\\S.*", message = "must not be blank") String name,
            @Size(max = 1000) String notes
    ) {}

    public record AddWorkoutExerciseRequest(@NotNull UUID exerciseId) {}

    public record ReorderRequest(@NotNull @Size(max = 30) List<@NotNull UUID> workoutExerciseIds) {}

    /** A blank value clears the notes. */
    public record UpdateWorkoutExerciseRequest(@NotNull @Size(max = 500) String notes) {}

    /**
     * {@code id} is optional and generated by the client: sending the same id again returns the set that
     * already exists instead of creating a second one, which makes retries safe.
     */
    public record CreateSetRequest(
            UUID id,
            @NotNull @DecimalMin("0") @DecimalMax("1000") @Digits(integer = 4, fraction = 2) BigDecimal weightKg,
            @NotNull @Min(1) @Max(100) Integer reps,
            @ValidRpe BigDecimal rpe,
            Boolean warmup
    ) {}

    /** All optional, at least one required. {@code clearRpe: true} removes the RPE. */
    public record UpdateSetRequest(
            @DecimalMin("0") @DecimalMax("1000") @Digits(integer = 4, fraction = 2) BigDecimal weightKg,
            @Min(1) @Max(100) Integer reps,
            @ValidRpe BigDecimal rpe,
            Boolean clearRpe,
            Boolean warmup
    ) {}

    // ---- responses ---------------------------------------------------------------------------

    public record SetResponse(UUID id, int setNumber, BigDecimal weightKg, int reps, BigDecimal rpe, boolean warmup,
                              List<PersonalRecordType> personalRecords) {}

    public record SessionSet(BigDecimal weightKg, int reps) {}

    /** What the user did with this exercise the last time it appeared in a completed workout. */
    public record LastSession(LocalDate performedOn, List<SessionSet> sets) {}

    public record WorkoutExerciseResponse(UUID id, int position, String notes, ExerciseResponse exercise,
                                          LastSession lastSession, List<SetResponse> sets) {}

    public record WorkoutTotals(int exercises, int sets, int workingSets, BigDecimal volumeKg) {}

    public record WorkoutDetail(UUID id, String name, WorkoutStatus status, LocalDate performedOn, Instant startedAt,
                                Instant finishedAt, Long durationMinutes, String notes, UUID templateId,
                                WorkoutTotals totals, List<WorkoutExerciseResponse> exercises) {}

    public record WorkoutListItem(UUID id, String name, WorkoutStatus status, LocalDate performedOn, Instant startedAt,
                                  Instant finishedAt, Long durationMinutes, int exerciseCount, int setCount,
                                  BigDecimal volumeKg) {}
}
